<?php

namespace Versuch\stoerungsmelderBundle\Repository;

/**
 * AbteilungRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbteilungRepository extends \Doctrine\ORM\EntityRepository
{
}
