<?php

namespace Versuch\stoerungsmelderBundle\Repository;

/**
 * StoerungRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoerungRepository extends \Doctrine\ORM\EntityRepository
{
}
